version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: qdrant_container
    ports:
      - "${QDRANT_HTTP_PORT}:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HOST=0.0.0.0
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
volumes:
  qdrant_storage:
  ollama_data: